set-option -g set-clipboard on
set -g cursor-style bar
bind-key x set-window-option synchronize-panes \; display-message "synchronize-panes toggled"
bind-key 4 split-window -h \; split-window -v \; select-pane -t 0 \; split-window -v \; select-pane -t 0
